# Generated by Django 5.0.6 on 2024-07-15 16:36

import slnapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicdetailform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=25)),
                ('PanNumber', models.CharField(max_length=10, validators=[slnapp.models.validate_pan])),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_of_birth', models.DateField()),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=10)),
                ('Required_LoanAmount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
