# Generated by Django 5.0.6 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slnapp', '0002_basicdetailform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetailform',
            name='random_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
