# Generated by Django 5.0.6 on 2024-07-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slnapp', '0006_remove_applicant_bank_nbfc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('LAP', 'Loan Against Property'), ('LAPBT', 'Loan Against Property with Business Tenure')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('pan_card_number', models.CharField(max_length=10)),
                ('aadhar_card_number', models.CharField(max_length=12)),
                ('marital_status', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('current_address', models.TextField()),
                ('current_address_pincode', models.CharField(max_length=6)),
                ('aadhar_address', models.TextField()),
                ('aadhar_pincode', models.CharField(max_length=6)),
                ('income_source', models.CharField(choices=[('JOB', 'Job'), ('BUSINESS', 'Business')], max_length=10)),
                ('net_salary_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job_joining_date', models.DateField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('total_job_experience', models.IntegerField(blank=True, null=True)),
                ('net_income_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('business_establishment_date', models.DateField(blank=True, null=True)),
                ('gst_certificate', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nature_of_business', models.TextField(blank=True, null=True)),
                ('turnover_in_lakhs_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('required_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('existing_loan', models.BooleanField(default=False)),
                ('existing_loan_details', models.CharField(blank=True, max_length=100, null=True)),
                ('ref1_name', models.CharField(max_length=100)),
                ('ref1_mobile', models.CharField(max_length=15)),
                ('ref2_name', models.CharField(max_length=100)),
                ('ref2_mobile', models.CharField(max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('co_applicant_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('co_applicant_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('co_applicant_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('co_applicant_age', models.IntegerField(blank=True, null=True)),
                ('co_applicant_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('co_applicant_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('co_applicant_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('co_applicant_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('co_applicant_net_income_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
